name: move PR to main
on:
  pull_request:
    branches: [ master ]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          script: |
            github.issues.createIssueComment({
              owner: context.repo()[0],
              repo: context.repo()[1],
              issue_number: context.issue(),
              body: "This PR is against base branch 'master', but should be against 'main'. Please update the base branch accordingly.",
            })
